general.working_directory = "/Users/fernandofrali/Documents"

[window]
dimensions.columns = 140
dimensions.lines = 45
decorations = "Buttonless"
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9

[font]
normal.family = "JetBrains Mono"
normal.style = "Regular"
italic.style = "Italic"
bold.style = "Bold"
size = 14.0

[colors.primary]
background = "#101010"
foreground = "#cccccc"

[colors.cursor]
cursor = "#cccccc"
text   = "#101010"

[colors.selection]
background = "#282828"
text       = "#dddddd"

[colors.normal]
black   = "#2a2a2a"
red     = "#ba0959"
green   = "#1bfd9c"
yellow  = "#b4b4b4"
blue    = "#7a7a7a"
magenta = "#708090"
cyan    = "#66b2b2"
white   = "#f1f1f1"

[colors.bright]
black   = "#4a4a4a"
red     = "#fd1b7c"
green   = "#66ffad"
yellow  = "#dddddd"
blue    = "#aaaaaa"
magenta = "#879aad"
cyan    = "#49c4c4"
white   = "#ffffff"
