general.working_directory = "/Users/fernandofrali/Documents"

[window]
dimensions.columns = 140
dimensions.lines = 45
decorations = "Buttonless"
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
size = 14

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#000000'
cursor = '#CED773'

# Normal colors
[colors.normal]
black   = '#161616'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

# Bright colors
[colors.bright]
black   = '#525252'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

